# Generated by Django 4.0.3 on 2022-03-24 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendario_Tareas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impuesto', models.CharField(max_length=40)),
                ('codigo_impuesto', models.IntegerField()),
                ('fecha_vencimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('cuit', models.IntegerField(primary_key=True, serialize=False)),
                ('telefono', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Foro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=40)),
                ('contraseña', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Impuestos',
            fields=[
                ('impuesto', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=40)),
                ('codigo_impuesto', models.IntegerField(primary_key=True, serialize=False)),
                ('repeticion', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('documento', models.IntegerField(primary_key=True, serialize=False)),
                ('mail', models.EmailField(max_length=254)),
            ],
        ),
    ]
